### ISSUE TITLE
better error message for missing param types involving SAMs

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#155]
Function literals for SAM types introduces a source incompatibility in 2.12.
The following compiles in 2.11, but not in 2.12.
We should investigate if we can provide a specific error message for this case.

``` scala
abstract class S {
  def f(x: Int): Int
}
class C {
  def m(f: Int => Int) = 0
  def m(s: S) = 1

  def plus(x: Int) = x + 1

  def t1 = m(x => x + 1)
  def t2 = m(_ + 1)
}
```

gives

```
Test.scala:10: error: missing parameter type
  def t1 = m(x => x + 1)
             ^
Test.scala:11: error: missing parameter type for expanded function ((x$1: <error>) => x$1.$plus(1))
  def t2 = m(_ + 1)
             ^
two errors found
```

Also, is it right that the following continues to compile in current 2.12.x without an ambiguity error?

```
abstract class S {
  def f(x: Int): Int
}
class C {
  def m(f: Int => Int) = 0
  def m(s: S) = 1

  def plus(x: Int) = x + 1

  def t3 = m(plus(_))
}
```

**Comment by adriaanm** [comment]
The first issue was resolved in https://github.com/scala/scala/pull/5307, and the second is clarified in https://github.com/scala/scala/pull/4971/files#diff-c067e953d98d0b8fb993aeae8bdb0bd4R989
