### ISSUE TITLE
upgrade JIRA to latest 6.4.x release

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#300]
we are running 6.4.11 says https://issues.scala-lang.org/secure/admin/ViewSystemInfo.jspa

6.4.11 is from August 2015, says https://confluence.atlassian.com/jira064/jira-6-4-11-release-notes-776654084.html

6.4.14 is about a year newer https://confluence.atlassian.com/jira064/jira-6-4-14-release-notes-834232021.html and is presumably stable since that's a while ago now

I experience enough randomly JIRA flakiness I'm willing to hope the newer version might address some of it.

**Comment by lrytz** [comment]
cc @fsalvi - do you have time to upgrade jira? we can also move to the current version, which seems to be 7.3.1 (https://www.atlassian.com/software/jira/update). it's running on codrev@tresor-srv01.

**Comment by fsalvi** [comment]
Ok, I will have a look

**Comment by fsalvi** [comment]
I did an upgrade to 6.4.14 which is still supported for a few weeks:
6.4 (EOL Date: Mar 17, 2017)

I will test the latest version later. It seems there are some important modifications, so I will try it on a test environment before putting it in production.

**Comment by lrytz** [comment]
Great, thank you!

**Comment by SethTisue** [comment]
thanks Fabien!

**Comment by SethTisue** [comment]
@fsalvi curious, any update on this...? on the one hand it's not urgent, but also, it would really would be nice to get on a current, supported version before too too long.

**Comment by fsalvi** [comment]
Ok, I did an upgrade to 7.0.11
Let me know if it's ok or if we need to revert to the old version.
If it looks good, I will put the latest 7.3.x in a few days...

**Comment by adriaanm** [comment]
Thanks! Not sure why, but I (user `moors`) can no longer close issues? Or at least, don't see a button/action for it.

**Comment by adriaanm** [comment]
Now I did get the close button, but JIRA crashed after I clicked it:

https://issues.scala-lang.org/browse/SI-8417

Log's referral number: e036bf66-4b8f-4091-8657-436a8436a874

```
java.lang.NoSuchMethodError: com.atlassian.jira.event.issue.IssueEvent.getUser()Lcom/atlassian/crowd/embedded/api/User;
	at org.openmrs.jira.listeners.AutowatchJiraListener.issueClosed(AutowatchJiraListener.java:85) [?:?]
	at com.atlassian.jira.event.issue.AbstractIssueEventListener.workflowEvent(AbstractIssueEventListener.java:138) [jira-api-7.0.11.jar:?]
	at com.atlassian.jira.event.issue.IssueEventListenerHandler$IssueEventInvoker.invoke(IssueEventListenerHandler.java:43) [IssueEventListenerHandler$IssueEventInvoker.class:?]
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher$1$1.run(AsynchronousAbleEventDispatcher.java:48) [atlassian-event-2.3.5.jar:?]
	
```

**Comment by adriaanm** [comment]
Maybe some of the plugins need to be updated? The autowatch one?

**Comment by adriaanm** [comment]
I updated the add-ons that were out of date, and disabled a few we don't use (e.g., hipchat and asana)

**Comment by adriaanm** [comment]
Weird, I can't close https://issues.scala-lang.org/browse/SI-10245. Maybe because it has issue links, which are implemented by an add-on that was temporarily incompatible?

**Comment by adriaanm** [comment]
Since they are duplicates, I'm just going to delete them.

**Comment by lrytz** [comment]
A user wrote on the contact form:

Trying to file an issue at https://issues.scala-lang.org just now. 

`{code}` blocks were broken, giving NoSuchMethodError: 

https://d3vv6lp55qjaqc.cloudfront.net/items/2u1y0i1n093y0Q1j122s/Screen%20Shot%202017-03-23%20at%2012.24.18%20AM.png 

Creating the JIRA gave no sign of succeeding but apparently made the issue silently, so I inadvertently created two identical issues: https://issues.scala-lang.org/browse/SI-10247 and https://issues.scala-lang.org/browse/SI-10248 

Trying to edit the title on one gave another NoSuchMethodError: 

https://cl.ly/233B0T2D172P/Screen%20Shot%202017-03-23%20at%2012.45.33%20AM.png.

**Comment by lrytz** [comment]
I deleted SI-10248.

Weird, on https://issues.scala-lang.org/browse/SI-10247 i don't see the "Close Issue" button. On other bugs it shows, for example https://issues.scala-lang.org/browse/SI-6217.

**Comment by lrytz** [comment]
https://issues.scala-lang.org/secure/admin/IntegrityChecker.jspa


 Check workflow entry states are correct
ERROR: SI-10244 - The workflow entry with id 50900 has an incorrect state. (JRA-4241)
ERROR: SI-10247 - The workflow entry with id 50903 has an incorrect state. (JRA-4241)

**Comment by fsalvi** [comment]
It seems the integrity checker doesn't return any error, now.
I fixed the collation warnings about the database. There are still 2 warnings that I will try to fix later.
Do you see any other problem ?

**Comment by fsalvi** [comment]
Hmm, looking at the logs (jira-data/log/atlassian-jira.log), we get a lot of "Unexpected error formatting macro: code".
I tried to disable the "JIRA Syntax Highlighter" plugin and we don't get anymore these warnings...

**Comment by fsalvi** [comment]
Last version of the plugin is 2 years old:
https://marketplace.atlassian.com/plugins/jira.plugin.syntaxhighlighter.macro.syntaxplugin/versions

It seems it cannot work with the latest jira 7.3 version.

**Comment by retronym** [comment]
I think I installed a custom version of that back in 2013 that defaulted
the language to Scala:

https://github.com/retronym/syntaxplugin-public

Disabling it for now is the right approach to get things up and running again.

**Comment by lrytz** [comment]
@fsalvi I just created a new issue now (17:29 local time). When clicking the "Create" button, there's no visual feedback, the dialog remains open, but the issue is created. This is the one I created: https://issues.scala-lang.org/browse/SI-10249. Looking at it, it has the problem of a missing "Close Issue" button. Do you see something in the logs?

**Comment by lrytz** [comment]
In the created issue, the `{code}` sections are messed up. I will not fix it for now so you can see how it looks.

**Comment by fsalvi** [comment]
In the logs:

2017-03-23 17:58:09,777 http-nio-8080-exec-15 ERROR fsalvi 1078x390x1 18wy9gf 128.178.154.12,128.178.154.101 /secure/QuickEditIssue.jspa [c.a.j.quickedit.action.QuickEditIssue] Exception occurred editing issue: java.lang.NoSuchMethodError: com.atlassian.jira.event.issue.IssueEvent.getUser()Lcom/atlassian/crowd/embedded/api/User;
java.lang.NoSuchMethodError: com.atlassian.jira.event.issue.IssueEvent.getUser()Lcom/atlassian/crowd/embedded/api/User;
        at org.openmrs.jira.listeners.AutowatchJiraListener.issueUpdated(AutowatchJiraListener.java:130)
        at com.atlassian.jira.event.issue.AbstractIssueEventListener.workflowEvent(AbstractIssueEventListener.java:126)
        at com.atlassian.jira.event.issue.IssueEventListenerHandler$IssueEventInvoker.invoke(IssueEventListenerHandler.java:43)
        at com.atlassian.event.internal.AsynchronousAbleEventDispatcher$1$1.run(AsynchronousAbleEventDispatcher.java:48)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
        at com.atlassian.event.internal.AsynchronousAbleEventDispatcher.dispatch(AsynchronousAbleEventDispatcher.java:107)
        at com.atlassian.event.internal.EventPublisherImpl.invokeListeners(EventPublisherImpl.java:160)
        at com.atlassian.event.internal.EventPublisherImpl.publish(EventPublisherImpl.java:79)
        at com.atlassian.jira.event.issue.DefaultIssueEventManager.publishEvent(DefaultIssueEventManager.java:120)
        at com.atlassian.jira.event.issue.DefaultIssueEventManager.publishAsRedundant(DefaultIssueEventManager.java:132)
        at com.atlassian.jira.event.issue.DefaultIssueEventManager.dispatchRedundantEvent(DefaultIssueEventManager.java:103)
        at com.atlassian.jira.issue.util.DefaultIssueUpdater.storeModifiedFields(DefaultIssueUpdater.java:95)
        at com.atlassian.jira.issue.util.DefaultIssueUpdater.doUpdate(DefaultIssueUpdater.java:50)
        at com.atlassian.jira.issue.managers.DefaultIssueManager.doUpdate(DefaultIssueManager.java:721)
        at com.atlassian.jira.issue.managers.DefaultIssueManager.updateIssue(DefaultIssueManager.java:706)
        at com.atlassian.jira.bc.issue.DefaultIssueService.update(DefaultIssueService.java:261)
        at com.atlassian.jira.bc.issue.DefaultIssueService.update(DefaultIssueService.java:241)
        ... 3 filtered
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:30)
        at com.sun.proxy.$Proxy335.update(Unknown Source)
        ... 3 filtered
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.atlassian.plugin.osgi.bridge.external.HostComponentFactoryBean$DynamicServiceInvocationHandler.invoke(HostComponentFactoryBean.java:161)
        at com.sun.proxy.$Proxy335.update(Unknown Source)
        at com.atlassian.jira.quickedit.action.QuickEditIssue.doExecute(QuickEditIssue.java:139)
        ... 1 filtered
        at com.atlassian.jira.action.JiraActionSupport.execute(JiraActionSupport.java:63)
        ... 7 filtered
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        ... 50 filtered
        at com.atlassian.greenhopper.jira.filters.ClassicBoardRouter.doFilter(ClassicBoardRouter.java:59)
        ... 151 filtered
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by fsalvi** [comment]
It seems we lost the default handler for code blocks, but I don't see why...

**Comment by adriaanm** [comment]
I think we have reached our limit of investing more effort in keeping JIRA running. Since we've been wanting to standardize on GitHub for some time now, it seems this time has come.

I'll change JIRA to no longer allow user/issue creation and add a note to point users to github. We of course should keep the instance running as an archive.

**Comment by adriaanm** [comment]
~~Hrm, and now https://issues.scala-lang.org/ is 503ing for me?~~
Ok, seems to be back

**Comment by adriaanm** [comment]
Did I upset JIRA by announcing the migration?  😐

**Comment by fsalvi** [comment]
I tried to restart it, but it doesn't change anything. I also tried to put back the syntax highlighter plugin with the latest version (which should work fine with jira 7.0). It seems the problem is not related. We do get an error even without any code block:


2017-03-23 18:31:14,067 http-nio-8080-exec-7 ERROR      [o.a.c.c.C.[.[localhost].[/].[action]] Servlet.service() for servlet [action] in context with path [] threw exception [Servlet execution threw an exception] with root cause
java.lang.NoSuchMethodError: com.atlassian.jira.event.issue.IssueEvent.getUser()Lcom/atlassian/crowd/embedded/api/User;
        at org.openmrs.jira.listeners.AutowatchJiraListener.issueCreated(AutowatchJiraListener.java:100)
        at com.atlassian.jira.event.issue.AbstractIssueEventListener.workflowEvent(AbstractIssueEventListener.java:124)
        at com.atlassian.jira.event.issue.IssueEventListenerHandler$IssueEventInvoker.invoke(IssueEventListenerHandler.java:43)
        at com.atlassian.event.internal.AsynchronousAbleEventDispatcher$1$1.run(AsynchronousAbleEventDispatcher.java:48)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
        at com.atlassian.event.internal.AsynchronousAbleEventDispatcher.dispatch(AsynchronousAbleEventDispatcher.java:107)
        at com.atlassian.event.internal.EventPublisherImpl.invokeListeners(EventPublisherImpl.java:160)
        at com.atlassian.event.internal.EventPublisherImpl.publish(EventPublisherImpl.java:79)
        at com.atlassian.jira.event.issue.DefaultIssueEventManager.publishEvent(DefaultIssueEventManager.java:120)
        at com.atlassian.jira.event.issue.DefaultIssueEventManager.publishAsRedundant(DefaultIssueEventManager.java:132)
        at com.atlassian.jira.event.issue.DefaultIssueEventManager.dispatchRedundantEvent(DefaultIssueEventManager.java:83)
        at com.atlassian.jira.workflow.function.event.FireIssueEventFunction.execute(FireIssueEventFunction.java:58)
        at com.opensymphony.workflow.AbstractWorkflow.executeFunction(AbstractWorkflow.java:1050)
        at com.opensymphony.workflow.AbstractWorkflow.transitionWorkflow(AbstractWorkflow.java:1446)
        at com.opensymphony.workflow.AbstractWorkflow.initialize(AbstractWorkflow.java:615)
        at com.atlassian.jira.workflow.OSWorkflowManager.createIssue(OSWorkflowManager.java:741)
        at com.atlassian.jira.issue.managers.DefaultIssueManager.createIssue(DefaultIssueManager.java:611)
        at com.atlassian.jira.issue.managers.DefaultIssueManager.createIssue(DefaultIssueManager.java:525)
        at com.atlassian.jira.bc.issue.DefaultIssueService.create(DefaultIssueService.java:182)
        at com.atlassian.jira.bc.issue.DefaultIssueService.create(DefaultIssueService.java:153)
        ... 3 filtered
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:30)
        at com.sun.proxy.$Proxy335.create(Unknown Source)
        ... 3 filtered
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.atlassian.plugin.osgi.bridge.external.HostComponentFactoryBean$DynamicServiceInvocationHandler.invoke(HostComponentFactoryBean.java:161)
        at com.sun.proxy.$Proxy335.create(Unknown Source)
        at com.atlassian.jira.quickedit.action.QuickCreateIssue.doExecute(QuickCreateIssue.java:270)
        ... 1 filtered
        at com.atlassian.jira.action.JiraActionSupport.execute(JiraActionSupport.java:63)
        ... 7 filtered
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        ... 50 filtered
        at com.atlassian.greenhopper.jira.filters.ClassicBoardRouter.doFilter(ClassicBoardRouter.java:59)
        ... 151 filtered
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

**Comment by adriaanm** [comment]
looks like the autowatch plugin is at fault:
> at org.openmrs.jira.listeners.AutowatchJiraListener.issueCreated(AutowatchJiraListener.java:100)

I disabled it

**Comment by SethTisue** [comment]
closing since issues.scala-lang.org seems to be more or less functioning now on version 7.0.11, and is read only now anyway since Adriaan is migrating the issues to GitHub. thanks Fabien!
