### ISSUE TITLE
Can't resolve to overloaded apply (regression 2.11.9 ?)

### ISSUE THREAD

**Issue by xuwei-k** [scala/scala-dev#352]
https://github.com/xuwei-k/apply-overload-2.11.9

```scala
import org.scalacheck.{Arbitrary, Gen}

case class Foo[A](x: Option[Int], y: A)

object Foo {
  // error
  implicit def arbitrary[A](implicit a: Arbitrary[A]): Arbitrary[Foo[A]] =
    Arbitrary(Gen.resultOf[Option[Int], A, Foo[A]](Foo.apply[A]))

  def apply[A](x: Int, y: A): Foo[A] = Foo(Some(x), y)
}
```

<hr />

```
[error]  found   : (Int, A) => example.Foo[A]
[error]  required: (Option[Int], A) => example.Foo[A]
[error]     Arbitrary(Gen.resultOf[Option[Int], A, Foo[A]](Foo.apply[A]))
[error]                                                             ^
```

<hr />

but this is ok (change method definition order)

```scala
object Foo {
  def apply[A](x: Int, y: A): Foo[A] = Foo(Some(x), y)

  // ok
  implicit def arbitrary[A](implicit a: Arbitrary[A]): Arbitrary[Foo[A]] =
    Arbitrary(Gen.resultOf[Option[Int], A, Foo[A]](Foo.apply[A]))
}
```

**Comment by sjrd** [comment]
If it's a 2.11.9 regression, it's most certainly caused by https://github.com/scala/scala/pull/5730. I have the impression that that PR was a very risky move for a last minor version of 2.11 ...

**Comment by adriaanm** [comment]
Thanks for the report and the detailed analysis! Since this is also broken in 2.12.1, it may not be scala/scala#5730, since those changes aren't in there

**Comment by adriaanm** [comment]
I'll report back when I figure out what's common between 2.11.9 and 2.12.1 that's causing this.

**Comment by adriaanm** [comment]
Now that we'll have a 2.11.10, I'm working on diagnosing this today before we cut 2.11.10.

**Comment by adriaanm** [comment]
I confirmed this compiles on 2.11.9 with scala/scala#5730 reverted. Looking into what I can do to support this use case. Still suspicious that it also fails on 2.12.1.

Minimal repro:
```
object Foo {
  // spurious error if:
  //   - this definition precedes that of apply (which is overloaded with the synthetic one derived from the case class)
  //   - AND `Foo.apply` is explicitly applied to `[A]` (no error if `[A]` is inferred)
  //
  def referToOverloadedApply[A]: Foo[A] = Foo.apply[A]("bla")
  //                                                   ^
  //  found   : String("bla")
  //  required: Int

  def apply[A](x: Int): Foo[A] = ???
}
case class Foo[A](x: String) // must be polymorphic
```

**Comment by ashawley** [comment]
It looks like it worked fine in the milestones, just not the release candidates:

| scala      | scalacheck | compiles           |
|------------|------------|--------------------|
| 2.12.0-M1  |     1.12.4 | :white_check_mark: |
| 2.12.0-M5  |     1.13.2 | :white_check_mark: |
| 2.12.0-RC1 |     1.13.2 | :x:		       |
| 2.12.0-RC2 |     1.13.2 | :x:                |

    $ sbt ++2.12.0-M1 compile
    [success] Total time: 100 s, completed Apr 4, 2017 3:21:31 PM
    $ sbt ++2.12.0-M5 compile
    [success] Total time: 165 s, completed Apr 4, 2017 3:34:24 PM
    $ sbt ++2.12.0-RC1 compile
    [error] apply-overload-2.11.9/Test.scala:10: type mismatch;
    [error]  found   : (Int, A) => example.Foo[A]
    [error]  required: (Option[Int], A) => example.Foo[A]
    [error]     Arbitrary(Gen.resultOf[Option[Int], A, Foo[A]](Foo.apply[A]))
    [error]                                                             ^
    [error] one error found
    [error] (compile:compileIncremental) Compilation failed
    [error] Total time: 46 s, completed Apr 4, 2017 3:47:30 PM
    $ sbt ++2.12.0-RC2 compile
    [error] apply-overload-2.11.9/Test.scala:10: type mismatch;
    [error]  found   : (Int, A) => example.Foo[A]
    [error]  required: (Option[Int], A) => example.Foo[A]
    [error]     Arbitrary(Gen.resultOf[Option[Int], A, Foo[A]](Foo.apply[A]))
    [error]                                                             ^
    [error] one error found
    [error] (compile:compileIncremental) Compilation failed
    [error] Total time: 279 s, completed Apr 4, 2017 3:53:25 PM

Dunno if that helps, or not.

**Comment by adriaanm** [comment]
It does, thank you!

**Comment by adriaanm** [comment]
(It's probably the fields refactoring, but will have to look in detail to be sure.)

**Comment by adriaanm** [comment]
Working on a separate fix for 2.12.2
